plugins {
id 'com.android.application'
}

android {
namespace "protectedwp.safespace"
compileSdk 35

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "protectedwp.safespace"  
    minSdk 29
    targetSdk 37
    versionCode 84
    versionName "84.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}

}

dependencies {
implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
}
